services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-global_services_db} 
      MYSQL_USER: ${DB_USERNAME:-admin}       
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}    
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql

networks:
  mysql:
    driver: bridge

volumes:
  mysql_data:
